char *strcpy(char *s1, const char *s2)
char *strncpy(char *s1, const char *s2, size_t n)
char *strcat(char *s1, const char *s2)
char *strncat(char *s1, const char *s2, size_t n)
char *strchr(const char *s, int c)
char *strrchr(const char *s, int c)
int strcmp(const char *s1, const char *s2)
int strncmp(const char *s1, const char *s2, size_t n)
size_t strspn(char *s1, const char *s2)
size_t strcspn(char *s1, const char *s2)
size_t strlen(const char *s)
char *strpbrk(const char *s1, const char *s2)
char *strstr(const char *s1, const char *s2)
char *strtok(char *s1, const char *s2)
char *strerror(int errnum);
