TEX_SRC = $(wildcard *.tex)

help:
	@echo "make all - to build all slides"
	@echo "make clean - to remove slides and builds artefacts"

build_pdf:
	pdflatex $(TEX_SRC)

clean_tex:
	rm -rf *.toc *.log *.nm *.aux *.nava *.snm *.nav *.vrb
clean_obj:
	rm -rf *.o core *.pdf *.out
