TEX_SRC = $(wildcard *.tex)

help:
	@echo "make all - to build all slides"
	@echo "make clean - to remove slides and builds artefacts"
	@echo "make arch - pack all slides to an archive"

build_pdf:
	pdflatex $(TEX_SRC)

clean_tex:
	rm -rf *.toc *.log *.nm *.aux *.nava *.snm *.nav *.vrb
clean_obj:
	rm -rf *.o core *.pdf *.out *.i *.s *.S *.a
